from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Date,
    DateTime,
    Index,
    Integer,
    Numeric,
    String,
    UniqueConstraint,
    desc,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.domain.enums import EventType, Severity
from app.models.base import Base

_SEVERITY_VALUES = ", ".join(f"'{s.value}'" for s in Severity if s is not Severity.NORMAL)
_EVENT_TYPE_VALUES = ", ".join(f"'{e.value}'" for e in EventType)


class ChangeEvent(Base):
    """A derived judgement that something meaningful happened to a symbol.

    Deliberately has no `user_id`, and must never acquire one. An event is a fact
    about the market, detected once: "NVDA moved 6% against its previous close".
    Ten thousand users watching NVDA produce one event and ten thousand cursors,
    not ten thousand events. It is also what lets the worker run without knowing
    that users exist at all.

    The per-user dimension lives entirely in user_seen_state.
    """

    __tablename__ = "change_events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    symbol: Mapped[str] = mapped_column(String(10), nullable=False)

    # The exchange-local session this event belongs to. Exists to back the
    # uniqueness constraint below.
    trading_day: Mapped[date] = mapped_column(Date, nullable=False)

    event_type: Mapped[str] = mapped_column(String(24), nullable=False)
    score: Mapped[int] = mapped_column(Integer, nullable=False)
    severity: Mapped[str] = mapped_column(String(16), nullable=False)

    # Human-readable reasons, generated by the same code that produced the
    # score. Stored rather than recomputed at read time so that the explanation
    # a user sees is the one that actually justified the decision, even after
    # thresholds are later retuned.
    evidence: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)

    # The inputs behind the score, kept for debugging and for the detail view.
    # Nullable because a signal can be unavailable (no volume baseline yet).
    price_pct: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    volume_ratio: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    confidence: Mapped[Decimal] = mapped_column(Numeric(4, 3), nullable=False)

    detected_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        # THE constraint that keeps the feed readable. A worker on a 5-minute
        # tick would otherwise generate ~78 near-identical "NVDA is up" events
        # per session. One row per symbol per session, escalated in place when
        # the score rises. This is what makes "refreshing does not duplicate
        # events" structurally true rather than something the UI hides.
        UniqueConstraint("symbol", "trading_day", name="uq_change_events_symbol_trading_day"),
        CheckConstraint("score >= 0 AND score <= 100", name="score_in_range"),
        # NORMAL is excluded on purpose: an event below the WATCH floor is not a
        # meaningful change, and storing one would break the meaning of the table.
        CheckConstraint(f"severity IN ({_SEVERITY_VALUES})", name="severity_valid"),
        CheckConstraint(f"event_type IN ({_EVENT_TYPE_VALUES})", name="event_type_valid"),
        CheckConstraint("confidence > 0 AND confidence <= 1", name="confidence_in_range"),
        CheckConstraint("jsonb_typeof(evidence) = 'array'", name="evidence_is_array"),
        # The change-feed read path: "events after this user's cursor". The feed
        # filters by detected_at across a set of symbols, so detected_at leads.
        Index("ix_change_events_detected_at", desc("detected_at")),
        Index("ix_change_events_symbol_detected_at", "symbol", desc("detected_at")),
        {"comment": "Derived meaningful changes. User-agnostic by design."},
    )

    def __repr__(self) -> str:
        return f"<ChangeEvent {self.symbol} {self.severity} score={self.score}>"
