"""initial schema

Revision ID: 51f1cb09acb0
Revises: 
Create Date: 2026-09-04 22:13:37.156278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51f1cb09acb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('PRICE_MOVE', 'VOLUME_SPIKE', 'PRICE_AND_VOLUME')", name=op.f('ck_change_events_event_type_valid')),
    sa.CheckConstraint("jsonb_typeof(evidence) = 'array'", name=op.f('ck_change_events_evidence_is_array')),
    sa.CheckConstraint("severity IN ('WATCH', 'IMPORTANT', 'HIGH')", name=op.f('ck_change_events_severity_valid')),
    sa.CheckConstraint('confidence > 0 AND confidence <= 1', name=op.f('ck_change_events_confidence_in_range')),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_change_events_score_in_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_events')),
    sa.UniqueConstraint('symbol', 'trading_day', name='uq_change_events_symbol_trading_day'),
    comment='Derived meaningful changes. User-agnostic by design.'
    )
    op.create_index('ix_change_events_detected_at', 'change_events', [sa.literal_column('detected_at DESC')], unique=False)
    op.create_index('ix_change_events_symbol_detected_at', 'change_events', ['symbol', sa.literal_column('detected_at DESC')], unique=False)
    op.create_table('daily_bars',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('close > 0', name=op.f('ck_daily_bars_close_positive')),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name=op.f('ck_daily_bars_volume_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_bars')),
    sa.UniqueConstraint('source', 'symbol', 'session_date', name='uq_daily_bars_session'),
    comment='Completed trading sessions, used as change-detection baselines'
    )
    op.create_index('ix_daily_bars_symbol_session_date', 'daily_bars', ['symbol', sa.literal_column('session_date DESC')], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('market_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingest_freshness', sa.String(length=16), nullable=False),
    sa.CheckConstraint("ingest_freshness IN ('FRESH', 'DELAYED', 'STALE')", name=op.f('ck_market_snapshots_ingest_freshness_valid')),
    sa.CheckConstraint('price > 0', name=op.f('ck_market_snapshots_price_positive')),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name=op.f('ck_market_snapshots_volume_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots')),
    sa.UniqueConstraint('source', 'symbol', 'market_timestamp', name='uq_market_snapshots_observation'),
    comment='Immutable observations from market data providers'
    )
    op.create_index('ix_market_snapshots_symbol_market_timestamp', 'market_snapshots', ['symbol', sa.literal_column('market_timestamp DESC')], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_is_lowercase')),
    sa.CheckConstraint('length(email) >= 3', name=op.f('ck_users_email_min_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_watchlists_name_not_blank')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watchlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlists_user_id_name'),
    comment='User-created lists of symbols'
    )
    op.create_index('ix_watchlists_user_id', 'watchlists', ['user_id'], unique=False)
    op.create_table('user_seen_state',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('watchlist_id', sa.Uuid(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_event_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_event_id'], ['change_events.id'], name=op.f('fk_user_seen_state_last_seen_event_id_change_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_seen_state_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_user_seen_state_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'watchlist_id', name=op.f('pk_user_seen_state'))
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('watchlist_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("symbol ~ '^[A-Z][A-Z0-9.\\-]{0,9}$'", name=op.f('ck_watchlist_items_symbol_format')),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_items_watchlist_id_symbol'),
    comment='Symbols belonging to a watchlist'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('user_seen_state')
    op.drop_index('ix_watchlists_user_id', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_market_snapshots_symbol_market_timestamp', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_daily_bars_symbol_session_date', table_name='daily_bars')
    op.drop_table('daily_bars')
    op.drop_index('ix_change_events_symbol_detected_at', table_name='change_events')
    op.drop_index('ix_change_events_detected_at', table_name='change_events')
    op.drop_table('change_events')
    # ### end Alembic commands ###
